energizer_worker:
  cron: "0 0 1 1 *" # At 00:00 on day-of-month 1 in January.
  class: "EnergizerWorker"
  queue: "energizer"
billing_worker:
  cron: "0 1 1 */1 *" # At 01:00 on day-of-month 5.
  class: "BatchBillingWorker"
  queue: "billing"