default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>

development:
  <<: *default

test:
  <<: *default
